### ISSUE TITLE
GrowersHouse | Order callback issue

### ISSUE THREAD

**Issue by DirkUnk** [pricewaiter/magento#3]
@bobbyburden 

Growershouse is reporting an issue with the Magento order call back feature. Everything is properly configured in his PW admin settings and all his other orders are properly importing.

Can you take a look and see why this one order (Transaction ID:
6836654710) did not import?  Check your inbox for more info.

**Comment by bobbyburden** [comment]
@mikejestes can you see if there was anything odd or different about the Order Callback for GrowersHouse Transaction ID `6836654710`?

**Comment by mikejestes** [comment]
Our post data`
```
url: http://growershouse.com/pricewaiter/callback
 postData.pricewaiter_id: 81337
 postData.order_completed_timestamp: 2015-01-14T18:36:42+00:00
 postData.store_id: 370
 postData.store_name: GrowersHouse
 postData.api_key: xdSNpjHnpURDZkE0GYRgfPOiMpef8TDbihok3voKVFDXEZx3Mf
 postData.transaction_id: 6836654710
 postData.payment_method: authorize_net
 postData.buyer_first_name: Terresa
 postData.buyer_last_name: Rennhack
 postData.buyer_name: Terresa Rennhack
 postData.buyer_email: trennhack@gmail.com
 postData.buyer_shipping_name: Terresa Rennhack
 postData.buyer_shipping_first_name: Terresa
 postData.buyer_shipping_last_name: Rennhack
 postData.buyer_shipping_address: 10099 wooley road
 postData.buyer_shipping_address2: 
 postData.buyer_shipping_address3: 
 postData.buyer_shipping_city: Live Oak
 postData.buyer_shipping_state: CA
 postData.buyer_shipping_zip: 95953
 postData.buyer_shipping_phone: 4088071482
 postData.buyer_shipping_country: US
 postData.buyer_billing_name: 
 postData.buyer_billing_first_name: Terresa
 postData.buyer_billing_last_name: Rennhack
 postData.buyer_billing_address: 316 chateau la salle drive
 postData.buyer_billing_address2: 
 postData.buyer_billing_address3: 
 postData.buyer_billing_city: San Jose
 postData.buyer_billing_state: CA
 postData.buyer_billing_zip: 95111
 postData.buyer_billing_phone: 4088071482
 postData.buyer_billing_country: US
 postData.quantity: 1
 postData.unit_price: 45.00
 postData.tax: 0.00
 postData.shipping: 0.00
 postData.total: 45.00
 postData.shipping_method: FedEx
 postData.product_sku: APT-MB-
 postData.product_name: Aptus MassBoost - Bud Booster
 postData.test: 0
 postData.product_option_count: 0
```
